import type { Metadata } from "next";
import {  Manrope   } from "next/font/google";
import "./globals.css";
import Nav from "@/components/Nav";
import Footer from "@/components/Footer";

const manrope = Manrope({subsets: ["latin"] , display: "swap" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={manrope.className}>
        <Nav />
        <div className="h-[1px] bg-white opacity-10"></div>
        {children}
        <Footer/>
        </body>
    </html>
  );
}
